# -*- coding: utf-8 -*-
"""Life Science 2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-GT9MACDPnUkuDK-WQLhpnQGJiEDhmRj

# Life Science at SSIS 2022-2023

There is a lot to come. Will we have 4 or 5 topics? What about the retake policy?
"""

lessons   = 90
exams     = 10
semesters = 4
units     = 5

lessons_per_unit = lessons / units
units_per_semester = units / semesters

print(f"We will have {lessons_per_unit} lessons per unit and on average {units_per_semester} units per semester.")